export const db = [
  {
    id: 1,
    title: 'adsfasdfasdfasfasfasfasfsdasdf',
    mainText: '1번 째 글안녕하ㅔ요 저는 이재진입니다. ',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재진',
    board: 3,
    thumbnailImg:
      'https://cloudfront-ap-northeast-1.images.arcpublishing.com/chosun/UVBJZL3RXAB36BDSHVM3MW2WNY.jpg',
  },
  {
    id: 2,
    title: '제목입니다.',
    mainText: '2번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이자진',
    board: 2,
    thumbnailImg:
      'https://cloudfront-ap-northeast-1.images.arcpublishing.com/chosun/UVBJZL3RXAB36BDSHVM3MW2WNY.jpg',
  },
  {
    id: 3,
    title: '3333',
    mainText: '3번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이죄진',
    board: 2,
    thumbnailImg:
      'https://cloudfront-ap-northeast-1.images.arcpublishing.com/chosun/UVBJZL3RXAB36BDSHVM3MW2WNY.jpg',
  },
  {
    id: 4,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 2,
  },
  {
    id: 5,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 6,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 7,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 8,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 9,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 10,
    title: 'adsfasdfasdfasfasfasfasfsdasdf',
    mainText:
      '1번 째 글안녕하ㅔ요 저는 이재진입니다. adsfasfdsdaffffffffffffffffffffffffdfasdfasdfasfasdfasfasfasdf',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재진',
    board: 3,
  },
  {
    id: 11,
    title: '제목입니다.',
    mainText: '2번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이자진',
    board: 1,
  },
  {
    id: 12,
    title: '3333',
    mainText: '3번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이죄진',
    board: 1,
  },
  {
    id: 13,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 3,
  },
  {
    id: 14,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 15,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 16,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 17,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 1,
  },
  {
    id: 18,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 3,
  },
  {
    id: 19,
    title: 'adsfasdfasdfasfasfasfasfsdasdf',
    mainText:
      '1번 째 글안녕하ㅔ요 저는 이재진입니다. adsfasfdsdaffffffffffffffffffffffffdfasdfasdfasfasdfasfasfasdf',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재진',
    board: 4,
  },
  {
    id: 20,
    title: '제목입니다.',
    mainText: '2번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이자진',
    board: 4,
  },
  {
    id: 21,
    title: '3333',
    mainText: '3번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이죄진',
    board: 4,
  },
  {
    id: 22,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 23,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
  {
    id: 24,
    title: '4444',
    mainText: '4번 째 글',
    img: 'https://static.vecteezy.com/system/resources/previews/005/544/718/non_2x/profile-icon-design-free-vector.jpg',
    name: '이재줴',
    board: 4,
  },
];
